apiVersion: castai.aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws-castai
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: platform-ref-aws-castai
    region: us-west-2
    version: "1.27"
    iam:
      roleArn: arn:aws:iam::609897127049:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
    nodes:
      count: 3 
      instanceType: t3.small
      image: bottlerocket-aws-k8s-1.27-x86_64*
      deleteNodesOnDisconnect: true
    gitops:
      git:
        url: https://github.com/upbound/platform-ref-aws-castai/
        ref:
          name: refs/heads/main
  writeConnectionSecretToRef:
    name: platform-ref-aws-castai-kubeconfig